#Logistic Regression On Attrition Regresion

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Day24/general_data.csv')

In [3]:
df.head()

   Age Attrition  ... YearsSinceLastPromotion YearsWithCurrManager
0   51        No  ...                       0                    0
1   31       Yes  ...                       1                    4
2   32        No  ...                       0                    3
3   38        No  ...                       7                    5
4   32        No  ...                       0                    4

[5 rows x 24 columns]

In [4]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [5]:
df.drop_duplicates()

      Age Attrition  ... YearsSinceLastPromotion YearsWithCurrManager
0      51        No  ...                       0                    0
1      31       Yes  ...                       1                    4
2      32        No  ...                       0                    3
3      38        No  ...                       7                    5
4      32        No  ...                       0                    4
...   ...       ...  ...                     ...                  ...
4405   42        No  ...                       0                    2
4406   29        No  ...                       0                    2
4407   25        No  ...                       1                    2
4408   42        No  ...                       7                    8
4409   40        No  ...                       3                    9

[4410 rows x 24 columns]

In [6]:
mean_noOfComp = df['NumCompaniesWorked'].mode()

In [7]:
new_noOFComp = np.where(df['NumCompaniesWorked'].isnull(),mean_noOfComp,df['NumCompaniesWorked'])
df['NumCompaniesWorked'] = new_noOFComp

In [8]:
mode_totWork = df['TotalWorkingYears'].mode()

In [9]:
newTotWork = np.where(df['TotalWorkingYears'].isnull(),mode_totWork,df['TotalWorkingYears'])
df['TotalWorkingYears'] = newTotWork

In [10]:
df.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
EmployeeCount              0
EmployeeID                 0
Gender                     0
JobLevel                   0
JobRole                    0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
Over18                     0
PercentSalaryHike          0
StandardHours              0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()

In [13]:
df['Attrition'] = le.fit_transform(df['Attrition']) 
df['BusinessTravel'] = le.fit_transform(df['BusinessTravel']) 
df['Department'] = le.fit_transform(df['Department']) 
df['EducationField'] = le.fit_transform(df['EducationField']) 
df['Gender'] = le.fit_transform(df['Gender']) 
df['JobRole'] = le.fit_transform(df['JobRole']) 
df['MaritalStatus'] = le.fit_transform(df['MaritalStatus']) 
df['Over18'] = le.fit_transform(df['Over18'])

In [14]:
Y = df['Attrition']

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      4410 non-null   int64
 1   Attrition                4410 non-null   int64
 2   BusinessTravel           4410 non-null   int64
 3   Department               4410 non-null   int64
 4   DistanceFromHome         4410 non-null   int64
 5   Education                4410 non-null   int64
 6   EducationField           4410 non-null   int64
 7   EmployeeCount            4410 non-null   int64
 8   EmployeeID               4410 non-null   int64
 9   Gender                   4410 non-null   int64
 10  JobLevel                 4410 non-null   int64
 11  JobRole                  4410 non-null   int64
 12  MaritalStatus            4410 non-null   int64
 13  MonthlyIncome            4410 non-null   int64
 14  NumCompaniesWorked       4410 non-null   float64
 15  Over18                   4410 non-null   int64
 16  PercentSalaryHike        4410 non-null   int64
 17  StandardHours            4410 non-null   int64
 18  StockOptionLevel         4410 non-null   int64
 19  TotalWorkingYears        4410 non-null   float64
 20  TrainingTimesLastYear    4410 non-null   int64
 21  YearsAtCompany           4410 non-null   int64
 22  YearsSinceLastPromotion  4410 non-null   int64
 23  YearsWithCurrManager     4410 non-null   int64
dtypes: float64(2), int64(22)
memory usage: 827.0 KB

In [16]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [30]:
X = df[['Age','BusinessTravel','Department','DistanceFromHome','EducationField','Gender','JobLevel','JobRole','MaritalStatus','YearsWithCurrManager','YearsSinceLastPromotion','YearsAtCompany','TrainingTimesLastYear','MonthlyIncome','EmployeeCount']]

In [31]:
df.head()

   Age  Attrition  ...  YearsSinceLastPromotion  YearsWithCurrManager
0   51          0  ...                        0                     0
1   31          1  ...                        1                     4
2   32          0  ...                        0                     3
3   38          0  ...                        7                     5
4   32          0  ...                        0                     4

[5 rows x 24 columns]

In [32]:
import statsmodels.api as sm

In [33]:
X1 = sm.add_constant(X)

In [34]:
Logistic = sm.Logit(Y,X1)

In [35]:
result = Logistic.fit()

Optimization terminated successfully.
         Current function value: 0.399477
         Iterations 7

In [36]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:              Attrition   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4395
Method:                           MLE   Df Model:                           14
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                 0.09558
Time:                        14:14:35   Log-Likelihood:                -1761.7
converged:                       True   LL-Null:                       -1947.9
Covariance Type:            nonrobust   LLR p-value:                 8.308e-71
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Age                        -0.0403      0.005     -7.734      0.000      -0.050      -0.030
BusinessTravel             -0.0329      0.065     -0.506      0.613      -0.160       0.094
Department                 -0.2227      0.080     -2.780      0.005      -0.380      -0.066
DistanceFromHome           -0.0001      0.005     -0.028      0.978      -0.011       0.010
EducationField             -0.1014      0.033     -3.061      0.002      -0.166      -0.036
Gender                      0.0663      0.089      0.749      0.454      -0.107       0.240
JobLevel                   -0.0261      0.039     -0.668      0.504      -0.103       0.051
JobRole                     0.0343      0.018      1.935      0.053      -0.000       0.069
MaritalStatus               0.5672      0.063      9.064      0.000       0.445       0.690
YearsWithCurrManager       -0.1383      0.022     -6.323      0.000      -0.181      -0.095
YearsSinceLastPromotion     0.1321      0.020      6.498      0.000       0.092       0.172
YearsAtCompany             -0.0364      0.016     -2.294      0.022      -0.067      -0.005
TrainingTimesLastYear      -0.1439      0.035     -4.105      0.000      -0.213      -0.075
MonthlyIncome           -2.085e-06   9.55e-07     -2.184      0.029   -3.96e-06   -2.14e-07
EmployeeCount               0.4723      0.324      1.460      0.144      -0.162       1.107
===========================================================================================
"""

# As the import variable to consider are
* Age
* Department
* EducationField
* YearsWithCurrManager
* YearsSinceLastPromotion
*YearsAtCompany
*TrainingTimesLastYear
*MonthlyIncome
*EmployeeCount